---
- hosts: ws
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Install packages
      yum:
        state: present
        name:
          - docker
          - wget
          - lsof
          - passwd
          - unzip
          - java-11*
    - name: create directory
      file:
        path: /opt/qa/spg 
        state: directory
    - name: create file
      file: 
        path: /opt/qa/spg/spg.log
        state: touch 
    - name: start and enable daemon
      systemd_service:
        name: docker
        state: started
        enabled: yes          